# default configuration
baseURL = "/"
languageCode = "en-us"
title = "Bruglife Perspectives"
summaryLength = "10"
paginate = 4

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"

[[params.plugins.css]]
link = "plugins/themify/css/themify-icons.css"

[[params.plugins.css]]
link = "plugins/owl-carousel/owl.carousel.min.css"

[[params.plugins.css]]
link = "plugins/owl-carousel/owl.theme.default.min.css"

[[params.plugins.css]]
link = "plugins/animated-text/animated-text.css"


# js plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"

[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"

[[params.plugins.js]]
link = "plugins/owl-carousel/owl.carousel.min.js"

[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"

[[params.plugins.js]]
link = "plugins/animated-text/animated-text.js"

[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


# menu
[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 2

[[menu.main]]
URL = "contact"
name = "Contact"
weight = 3

# default parameters
[params]
home = "Home"
logo = "images/logo.png"
# contact info
mobile = "712-240-2517"
email = "bruggom@gmail.com"
address = "Des Moines, Iowa"
# meta description
author = "Marcus Bruggom"
description = "Providing unique photograph adventures specializing in non-traditional portraiture and architectural perspectives."
# google analitycs
google_analitycs_id = ""
# contact form action 
contact_form_action = "#" # contact form works with : https://formspree.io
# copyright
copyright = "Copyrighht &copy; 2020 a theme by [Bruglife Perspectives](https://www.bruglifeperspectives.com)"

# preloader
[params.preloader]
enable = true
preloader = "" # use png, jpg, svg or gif format

# google map
[params.gmap]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

# social site
[[params.social]]
icon = "ti-facebook"
URL = "https://www.facebook.com/Bruglifeperspectives"

[[params.social]]
icon = "ti-instagram"
URL = "https://www.instagram.com/bruglifeperspectives/"
